name: Test Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
    
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build
      
    - name: Test Docker build
      run: docker build -t portfolio-test .