name: Test & Docker Backup Pipeline

on: [push]

jobs:
  test-and-backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Node.js setup and tests
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
    
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build

    # Docker build and push
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Build & Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio:latest
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio:latest ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio:${{ github.sha }}